version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

# greater than symbol breaks this onto a different line (readability)
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
